handle ctrl-c

diff --git a/tools/build-loop b/tools/build-loop
--- a/tools/build-loop
+++ b/tools/build-loop
@@ -1,12 +1,21 @@
 #!/bin/bash
 
+TRAPPING=0
+trap "{ echo finishing; TRAPPING=1; }" SIGINT
+
 while :
 do
   tools/build
-  if [ "$?" == "0" ]; then
+  RET=$?
+  if [ $RET -eq 0 ]; then
     echo "success"
   else
-    echo "error"
+    echo "error: $RET"
   fi
-  sleep 1
+  if [ $TRAPPING -eq 0 ]; then
+    sleep 1
+  else
+    echo "done"
+    exit 0
+  fi
 done
